version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_SERVER=mssql
      - DB_DATABASE=DocumentManagement
      - DB_USER=sa
      - DB_PASSWORD=YourStrong@Passw0rd
      - PORT=3000
    volumes:
      - ./public/uploads:/app/public/uploads
    depends_on:
      mssql:
        condition: service_healthy

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'YourStrong@Passw0rd' -Q 'SELECT 1' -b -o /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s

volumes:
  mssql_data: 